# Generated by Django 4.2.5 on 2023-11-04 09:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0007_alter_blogs_blog_user_alter_notes_note_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=1000)),
                ('post_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('post_desc', tinymce.models.HTMLField()),
                ('post_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostImagess',
            fields=[
                ('images_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_images', models.FileField(upload_to='Posts')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.post')),
            ],
        ),
    ]
