# Generated by Django 4.2.5 on 2023-11-04 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_post_postimagess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='telegram',
            new_name='linkedin',
        ),
    ]
