# Generated by Django 4.2.5 on 2023-11-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_telegram_profilemodel_linkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='Photos'),
        ),
    ]
