# Generated by Django 4.2.5 on 2023-11-07 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_profilemodel_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='profile_image',
        ),
    ]
