# Generated by Django 4.2.5 on 2023-12-06 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='blog_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='note_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='project_user',
            new_name='user',
        ),
    ]
