# Generated by Django 4.2.5 on 2023-12-06 10:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0013_rename_blog_user_blogs_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Css',
            fields=[
                ('css_id', models.AutoField(primary_key=True, serialize=False)),
                ('css_title', models.CharField(max_length=1000)),
                ('css_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('css_desc', tinymce.models.HTMLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Java',
            fields=[
                ('java_id', models.AutoField(primary_key=True, serialize=False)),
                ('java_title', models.CharField(max_length=1000)),
                ('java_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('java_desc', tinymce.models.HTMLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_user',
            new_name='user',
        ),
        migrations.CreateModel(
            name='PythonImagess',
            fields=[
                ('images_id', models.AutoField(primary_key=True, serialize=False)),
                ('python_images', models.FileField(upload_to='Posts')),
                ('python_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.post')),
            ],
        ),
        migrations.CreateModel(
            name='Python',
            fields=[
                ('python_id', models.AutoField(primary_key=True, serialize=False)),
                ('python_title', models.CharField(max_length=1000)),
                ('python_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('python_desc', tinymce.models.HTMLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JavaImagess',
            fields=[
                ('images_id', models.AutoField(primary_key=True, serialize=False)),
                ('java_images', models.FileField(upload_to='Posts')),
                ('java_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.java')),
            ],
        ),
        migrations.CreateModel(
            name='CssImagess',
            fields=[
                ('images_id', models.AutoField(primary_key=True, serialize=False)),
                ('css_images', models.FileField(upload_to='Posts')),
                ('css_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.css')),
            ],
        ),
    ]
